backend/api/urls.py
from django.urls import include, path, re_path
from drf_yasg import openapi
from drf_yasg.views import get_schema_view
from rest_framework import permissions
from rest_framework.routers import DefaultRouter

from .orders_views import OrderViewSet, ShoppingCartViewSet
from .products_views import (
    CategoryViewSet,
    ComponentViewSet,
    CouponViewSet,
    FavoriteProductViewSet,
    ProducerViewSet,
    ProductViewSet,
    PromotionViewSet,
    SubcategoryViewSet,
    TagViewSet,
)
from .recipes_views import RecipeViewSet
from .reviews_views import ReviewViewSet
from .users_views import (
    AddressViewSet,
    CustomTokenCreateView,
    CustomTokenDestroyView,
    CustomUserViewSet,
)

app_name = "api"

router = DefaultRouter()
router.register("categories", CategoryViewSet)
router.register("subcategories", SubcategoryViewSet)
router.register("components", ComponentViewSet)
router.register("tags", TagViewSet)
router.register("producers", ProducerViewSet)
router.register("promotions", PromotionViewSet)
router.register("coupons", CouponViewSet)
router.register("products", ProductViewSet)
router.register(
    r"products/(?P<product_id>\d+)/reviews", ReviewViewSet, basename="reviews"
)
router.register("favorite-products", FavoriteProductViewSet)
router.register("users", CustomUserViewSet)
router.register(
    r"users/(?P<user_id>\d+)/addresses", AddressViewSet, basename="addresses"
)
router.register("shopping_cart", ShoppingCartViewSet, basename="shopping_carts")
router.register("order", OrderViewSet, basename="orders")
router.register("recipes", RecipeViewSet)

urlpatterns = [
    path("", include(router.urls)),
    path("", include("djoser.urls")),
    path("token/login/", CustomTokenCreateView.as_view(), name="login"),
    path("token/logout/", CustomTokenDestroyView.as_view(), name="logout"),
]

schema_view = get_schema_view(
    openapi.Info(
        title="Good Food API",
        default_version="v1",
        description="API documentation for the GoodFood project",
        contact=openapi.Contact(email="healthyfoodapi@yandex.ru"),
        license=openapi.License(name="MIT License"),
    ),
    public=True,
    permission_classes=(permissions.AllowAny,),
)

urlpatterns += [
    re_path(
        r"^swagger(?P<format>\.json|\.yaml)$",
        schema_view.without_ui(cache_timeout=0),
        name="schema-json",
    ),
    re_path(
        r"^swagger/$",
        schema_view.with_ui("swagger", cache_timeout=0),
        name="schema-swagger-ui",
    ),
    re_path(
        r"^redoc/$", schema_view.with_ui("redoc", cache_timeout=0), name="schema-redoc"
    ),
]

backend/good_food/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("admin/", admin.site.urls),
    path("api/", include("api.urls")),
    path("", include("payments.urls")),
]

if settings.DEBUG:
    import debug_toolbar

    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += (path("__debug__/", include(debug_toolbar.urls)),)

backend/payments/urls.py
from django.urls import path

from . import views

app_name = "payments"

urlpatterns = [
    path("pay/<int:pk>/", views.OrderPayView.as_view(), name="pay"),
    path("config/", views.stripe_config),
    path(
        "create-checkout-session/<int:order_id>/",
        views.create_checkout_session,
        name="create-checkout-session",
    ),
    path("payment-is-processing/", views.SuccessView.as_view()),
    path("payment-cancelled/", views.CancelledView.as_view()),
    path("webhooks/stripe/", views.stripe_webhook, name="stripe-webhook"),
]

backend/templates/cancel.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Отмена</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bulma@0.9.4/css/bulma.min.css">
    <script defer src="https://use.fontawesome.com/releases/v6.4.0/js/all.js"></script>
  </head>
  <body>
  <section class="section">
    <div class="container">
      <p>
        Ваш платеж был отменен!
        Если у вас возникли какие-либо вопросы, пожалуйста, свяжитесь с нами по адресу 
        <a href="mailto:healthyfoodapi@yandex.ru">healthyfoodapi@yandex.ru</a>.
      </p>
    </div>
  </section>
  </body>
</html>

backend/templates/cancelled.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Django + Stripe Checkout</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bulma@0.9.4/css/bulma.min.css">
    <script defer src="https://use.fontawesome.com/releases/v6.4.0/js/all.js"></script>
  </head>
  <body>
  <section class="section">
    <div class="container">
      <p>Your payment was cancelled.</p>
    </div>
  </section>
  </body>
</html>

backend/templates/home.html
{% load static %}

<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Оплата заказа</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bulma@0.9.4/css/bulma.min.css">
    <script src="https://js.stripe.com/v3/"></script>
    <script src="{% static 'main.js' %}"></script>
    <script defer src="https://use.fontawesome.com/releases/v6.4.0/js/all.js"></script>
  </head>
  <body>
    <h1>
      Оплата заказа {{ order }}
    </h1>
  <section class="section">
    <div class="container">
      <form action="{% url 'payments:create-checkout-session' order.id %}" method="POST">
        {% csrf_token %}
        <button class="button is-primary" id="submitBtn" type="submit">
          Оплатить заказ
        </button>
      </form>
    </div>
  </section>
  </body>
</html>

backend/templates/success.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Заказ оплачен</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bulma@0.9.4/css/bulma.min.css">
    <script defer src="https://use.fontawesome.com/releases/v6.4.0/js/all.js"></script>
  </head>
  <body>
  <section class="section">
    <div class="container">
      <p>
        Ваш заказ оплачен.
        Если у вас возникли какие-либо вопросы, пожалуйста, свяжитесь с нами по адресу
        <a href="mailto:healthyfoodapi@yandex.ru">healthyfoodapi@yandex.ru</a>.
      </p>
    </div>
  </section>
  </body>
</html>